apiVersion: apps/v1
kind: Deployment
metadata:
  name: neat-web-pod
  labels:
    app: neat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neat
  template:
    metadata:
      labels:
        app: neat
    spec:
      containers:
        - name: neat-web-container
          image: toelapiut/neat:0.1
